-- CREATE SCHEMA "public";

CREATE TABLE "public".dim_clientes ( 
	cliente_id           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tipo_cliente		 varchar(20) NOT NULL,
	fecha_nacimiento	 date NOT NULL,
	cliente_code         integer  NOT NULL ,
	sexo                 varchar(20)  NOT NULL ,
	cod_postal           varchar(10)  NOT NULL ,
	ciudad               varchar(100)  NOT NULL ,
	estado               varchar(100)  NOT NULL ,
	estudios             varchar(50)  NOT NULL ,
	ocupacion            varchar(100)  NOT NULL ,
	ingresos             varchar(100)  NOT NULL ,
	tiene_hijos          char(2)  NOT NULL ,
	CONSTRAINT pk_dim_clientes_cliente_id PRIMARY KEY ( cliente_id )
 );

COMMENT ON TABLE "public".dim_clientes IS 'Dimensión de clientes de la empresa';

COMMENT ON COLUMN "public".dim_clientes.cliente_id IS 'Clave subrogada de la dimensión de clientes';

COMMENT ON COLUMN "public".dim_clientes.cliente_code IS 'Identificador empresarial único del cliente';

COMMENT ON COLUMN "public".dim_clientes.sexo IS 'Sexo del cliente';

COMMENT ON COLUMN "public".dim_clientes.cod_postal IS 'Código postal del cliente';

COMMENT ON COLUMN "public".dim_clientes.ciudad IS 'Ciudad del cliente';

COMMENT ON COLUMN "public".dim_clientes.estado IS 'Pais o estado del cliente';

COMMENT ON COLUMN "public".dim_clientes.estudios IS 'Nivel de estudios del cliente';

COMMENT ON COLUMN "public".dim_clientes.ocupacion IS 'Ocupación laboral del cliente';

COMMENT ON COLUMN "public".dim_clientes.ingresos IS 'NIvel de ingresos del cliente';

COMMENT ON COLUMN "public".dim_clientes.tiene_hijos IS 'Indicador de si el cliente tiene hijos o no';

CREATE TABLE "public".dim_fecha ( 
	fecha_id             integer  NOT NULL ,
	fecha                date  NOT NULL ,
	anio                 smallint  NOT NULL ,
	trimestre            smallint  NOT NULL ,
	mes                  smallint  NOT NULL ,
	semana               integer  NOT NULL ,
	dia                  smallint  NOT NULL ,
	aniotrimestre        integer  NOT NULL ,
	aniomes              integer  NOT NULL ,
	aniosemana           integer  NOT NULL ,
	CONSTRAINT pk_dim_fecha_fecha_id PRIMARY KEY ( fecha_id )
 );

COMMENT ON TABLE "public".dim_fecha IS 'Dimensión de fechas';

COMMENT ON COLUMN "public".dim_fecha.fecha_id IS 'Identificador único de la fecha. Formato YYYYMMDD';

COMMENT ON COLUMN "public".dim_fecha.fecha IS 'Fecha';

COMMENT ON COLUMN "public".dim_fecha.anio IS 'Año de la fecha';

COMMENT ON COLUMN "public".dim_fecha.trimestre IS 'Número del trimestre del año';

COMMENT ON COLUMN "public".dim_fecha.mes IS 'Mes del año de la fecha';

COMMENT ON COLUMN "public".dim_fecha.semana IS 'Nº de semana del año';

COMMENT ON COLUMN "public".dim_fecha.dia IS 'Día del mes de la fecha';

COMMENT ON COLUMN "public".dim_fecha.aniotrimestre IS 'Concantenación del año y el número del trimestre. Formato YYYYQ';

COMMENT ON COLUMN "public".dim_fecha.aniomes IS 'Concatenación del año y del mes de la fecha. Formato YYYYMM';

COMMENT ON COLUMN "public".dim_fecha.aniosemana IS 'Concatenación del año y del número de la semana. Formato YYYYWW';

CREATE TABLE "public".dim_hora ( 
	hora_id              integer  NOT NULL ,
	horas                char(2)  NOT NULL ,
	minutos              char(2)  NOT NULL ,
	segundos             char(2)  NOT NULL ,
	hora_completa        char(8)  NOT NULL ,
	jornada              varchar(20)  NOT NULL ,
	CONSTRAINT pk_dim_hora_hora_id PRIMARY KEY ( hora_id )
 );

COMMENT ON TABLE "public".dim_hora IS 'Dimension de horas';

COMMENT ON COLUMN "public".dim_hora.hora_id IS 'Identificador del registro de la hora. Formato HHMMSS.';

COMMENT ON COLUMN "public".dim_hora.horas IS 'Hora. Formato HH';

COMMENT ON COLUMN "public".dim_hora.minutos IS 'Minutos. Formato MM.';

COMMENT ON COLUMN "public".dim_hora.segundos IS 'Segundos. Formato SS.';

COMMENT ON COLUMN "public".dim_hora.hora_completa IS 'Hora en formato HH:MM:SS';

COMMENT ON COLUMN "public".dim_hora.jornada IS 'Jornada a la que pertenece la hora: mañana, tarde o noche.';

CREATE TABLE "public".dim_producto ( 
	producto_id          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	product_number       varchar(25)   ,
	nombre               varchar(100)  NOT NULL ,
	interno              bool  NOT NULL ,
	vendible             bool  NOT NULL ,
	color                varchar(50)  NOT NULL ,
	talla                varchar(50)  NOT NULL ,
	peso                 numeric(8,2)  NOT NULL ,
	linea                varchar(20)  NOT NULL ,
	clase                varchar(20)  NOT NULL ,
	estilo               varchar(20)  NOT NULL ,
	categoria            varchar(100)  NOT NULL ,
	subcategoria         varchar(100)  NOT NULL ,
	CONSTRAINT pk_dim_producto_producto_id PRIMARY KEY ( producto_id )
 );

COMMENT ON TABLE "public".dim_producto IS 'Dimensión de productos de la empresa AdventureWorks';

COMMENT ON COLUMN "public".dim_producto.producto_id IS 'Identificador del registro del producto';

COMMENT ON COLUMN "public".dim_producto.product_number IS 'Clave de negocio del producto. Identificador único del mismo.';

COMMENT ON COLUMN "public".dim_producto.nombre IS 'Nombre del producto';

COMMENT ON COLUMN "public".dim_producto.interno IS 'El producto es interno si lo fabrica la propia empresa. Si no, es externo, es decir, se compra.';

COMMENT ON COLUMN "public".dim_producto.vendible IS 'El producto es vendible si se puede vender a los clientes.';

COMMENT ON COLUMN "public".dim_producto.color IS 'Color del producto.';

COMMENT ON COLUMN "public".dim_producto.talla IS 'Talla del producto';

COMMENT ON COLUMN "public".dim_producto.peso IS 'Peso del producto';

COMMENT ON COLUMN "public".dim_producto.linea IS 'Linea del producto: road, mountain, touring, standard';

COMMENT ON COLUMN "public".dim_producto.clase IS 'Clase o calidad del producto: alta, media o baja';

COMMENT ON COLUMN "public".dim_producto.estilo IS 'Estilo del producto: hombres, mujeres o universal.';

COMMENT ON COLUMN "public".dim_producto.categoria IS 'Categoría del producto';

COMMENT ON COLUMN "public".dim_producto.subcategoria IS 'Subcategoría del producto';

CREATE TABLE "public".dim_vendedor ( 
	vendedor_id          integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	vendedor_code        integer  NOT NULL ,
	sexo                 varchar(20)  NOT NULL ,
	fecha_nacimiento     date  NOT NULL ,
	region               varchar(50)  NOT NULL ,
	territorio           varchar(50)  NOT NULL ,
	CONSTRAINT pk_dim_vendedor_vendedor_id PRIMARY KEY ( vendedor_id )
 );

COMMENT ON TABLE "public".dim_vendedor IS 'Dimensión de vendedores (sales persons)';

COMMENT ON COLUMN "public".dim_vendedor.vendedor_id IS 'Clave subrogada del registro del vendedor';

COMMENT ON COLUMN "public".dim_vendedor.vendedor_code IS 'Corresponde con el business entity del vendedor.';

COMMENT ON COLUMN "public".dim_vendedor.sexo IS 'Sexo del vendedor';

COMMENT ON COLUMN "public".dim_vendedor.fecha_nacimiento IS 'Fecha de nacimiento del vendedor';

COMMENT ON COLUMN "public".dim_vendedor.region IS 'Region donde realiza su trabajo el vendedor';

COMMENT ON COLUMN "public".dim_vendedor.territorio IS 'Territorio, que es una subdivision de la region, donde realiza su trabajo el vendedor';

CREATE TABLE "public".fac_resenias ( 
	resenia_id           integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	fecha_id             integer  NOT NULL ,
	producto_id          integer  NOT NULL ,
	nota                 smallint  NOT NULL ,
	CONSTRAINT pk_fac_resenias_resenia_id PRIMARY KEY ( resenia_id ),
	CONSTRAINT fk_fac_resenias_dim_fecha FOREIGN KEY ( fecha_id ) REFERENCES "public".dim_fecha( fecha_id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_fac_resenias_dim_producto FOREIGN KEY ( producto_id ) REFERENCES "public".dim_producto( producto_id ) ON DELETE CASCADE ON UPDATE CASCADE
 );

COMMENT ON TABLE "public".fac_resenias IS 'Tabla de hechos de las reseñas de los consumidores sobre el producto.';

COMMENT ON COLUMN "public".fac_resenias.resenia_id IS 'Identificador del registro de la reseña';

COMMENT ON COLUMN "public".fac_resenias.fecha_id IS 'Identificador de la fecha de la reseña.';

COMMENT ON COLUMN "public".fac_resenias.producto_id IS 'Identificador del registro del producto.';

COMMENT ON COLUMN "public".fac_resenias.nota IS 'Nota (rating) asignada en la reseña. De 1 a 5.';

CREATE TABLE "public".fac_ventas ( 
	venta_id             integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	pedido_id            integer  NOT NULL ,
	producto_id          integer  NOT NULL ,
	fecha_id             integer  NOT NULL ,
	hora_id              integer  NOT NULL ,
	cliente_id           integer  NOT NULL ,
	vendedor_id          integer  NOT NULL ,
	cantidad             smallint  NOT NULL ,
	importe_unidad       numeric(13,2)  NOT NULL ,
	descuento_unidad     numeric(3,2)  NOT NULL ,
	importe_total        numeric(38,2)  NOT NULL ,
	coste_unidad         numeric(13,2)  NOT NULL ,
	coste_total          numeric(38,2)  NOT NULL ,
	margen_total         numeric(38,2)  NOT NULL ,
	CONSTRAINT pk_fac_ventas_venta_id PRIMARY KEY ( venta_id ),
	CONSTRAINT fk_fac_ventas_dim_clientes FOREIGN KEY ( cliente_id ) REFERENCES "public".dim_clientes( cliente_id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_fac_ventas_dim_fecha FOREIGN KEY ( fecha_id ) REFERENCES "public".dim_fecha( fecha_id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_fac_ventas_dim_producto FOREIGN KEY ( producto_id ) REFERENCES "public".dim_producto( producto_id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_fac_ventas_dim_vendedor FOREIGN KEY ( vendedor_id ) REFERENCES "public".dim_vendedor( vendedor_id ) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_fac_ventas_dim_hora FOREIGN KEY ( hora_id ) REFERENCES "public".dim_hora( hora_id ) ON DELETE CASCADE ON UPDATE CASCADE
 );

COMMENT ON TABLE "public".fac_ventas IS 'Tabla de hechos de las ventas realizadas';

COMMENT ON COLUMN "public".fac_ventas.venta_id IS 'Identificador del registro de la venta';

COMMENT ON COLUMN "public".fac_ventas.pedido_id IS 'Identificador del pedido';

COMMENT ON COLUMN "public".fac_ventas.producto_id IS 'Identificador del registro de la dimensión de productos.';

COMMENT ON COLUMN "public".fac_ventas.fecha_id IS 'Identificador de la fecha en la que se realiza el pedido';

COMMENT ON COLUMN "public".fac_ventas.hora_id IS 'Identificador de la hora en la que se realiza el pedido.';

COMMENT ON COLUMN "public".fac_ventas.cliente_id IS 'Identificador del registro del cliente que realiza el pedido';

COMMENT ON COLUMN "public".fac_ventas.vendedor_id IS 'Identificador del registro del vendedor que toma nota del pedido.';

COMMENT ON COLUMN "public".fac_ventas.cantidad IS 'Número de unidades del producto que se piden';

COMMENT ON COLUMN "public".fac_ventas.importe_unidad IS 'Importe de venta unitario del producto';

COMMENT ON COLUMN "public".fac_ventas.descuento_unidad IS 'Porcentaje de descuento que se aplica a cada unidad';

COMMENT ON COLUMN "public".fac_ventas.importe_total IS 'Importe total del producto una vez realizados los descuentos';

COMMENT ON COLUMN "public".fac_ventas.coste_unidad IS 'Coste unitario del producto';

COMMENT ON COLUMN "public".fac_ventas.coste_total IS 'Coste total de las unidades del producto solicitadas.';

COMMENT ON COLUMN "public".fac_ventas.margen_total IS 'Margen total obtenido por el pedido de este producto';

