version: "3"
services:
  elasticsearch:
    image: elasticsearch:5.6.4
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "exit", "0"]
  elastic-seed:
    build: elastic-seed
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:5.6.4
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  redis:
    image: redis
    ports:
      - "6379:6379"
  notebook:
    build: notebook
    ports:
      - "8888:8888"
    links:
      - elasticsearch
      - redis
